project:
  type: book
  output-dir: docs

book:
  title: "R Code for 'A Practical Guide . . .'"
  author: "John Maindonald"
  date: "2024-06-02"
  chapters:
    - index.qmd
    - ch1.qmd
    - ch2.qmd
    - ch3.qmd
    - ch4.qmd
    - ch5.qmd
    - ch6.qmd
    - ch7.qmd
    - ch8.qmd
    - ch9.qmd
    - Appendix.qmd

bibliography: references.bib

format:
  html:
    number-depth: 1
    theme: cosmo
    toc: true
    page-layout: full
  pdf:
    number-depth: 1
    documentclass: scrreprt
    toc: true
    



